<?php
$this->headLink()->appendStylesheet('//cdn.datatables.net/1.10.4/css/jquery.dataTables.css');
$this->headLink()->appendStylesheet('//cdn.datatables.net/plug-ins/9dcbecd42ad/integration/bootstrap/3/dataTables.bootstrap.css');
$this->inlineScript()->appendFile('//cdn.datatables.net/1.10.4/js/jquery.dataTables.min.js');
?>

<div id="welcome">
	<h4>Liste des utilisateurs</h4>
    <hr />
	 <a href="<?= $this->url(array(),'userAdd')?>" class="btn btn-success"><span class="glyphicon glyphicon-plus"> Nouvel utilisateur</span></a>
	<hr />
	<?= count($this->messages) ? '<p>'.implode('<br>', $this->messages).'</p>' : ''?>
	<table id="id_table" class="display" cellspacing="0" width="100%">
		<thead>
			<tr>
				<th>ID</th>
				<th>Username</th>
				<th>Type</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
		<?php 
		  foreach ($this->users as $user){ ?>
		<tr>
				<td><?= $user->getID()?></td>
				<td><?= $user->getName()?></td>
				<td><?= $user->getType_id()?></td>
				<td>
				    <a href="<?= $this->url(array('id' => $user->getId()),'userEdit')?>"class="btn btn-success"><span class="glyphicon glyphicon-edit"> Editer</span></a>
				    <a href="<?= $this->url(array('id' => $user->getId()),'userDelete')?>" class="btn btn-danger"><span class="glyphicon glyphicon-trash"> Supprimer</span></a>
				</td>
			</tr>
		<?php  }  ?>
    </tbody>
	</table>
</div>
<script type="text/javascript">
<?php $this->inlineScript()->captureStart()?>
$(document).ready( function () {
    $('#id_table').DataTable();
} );
<?php $this->inlineScript()->captureEnd()?>
</script>
