<?= $this->doctype().PHP_EOL?>
<html>
<head>
<?= $this->headTitle() .PHP_EOL?>
<?= $this->headMeta()->appendName('viewport', 'width =device-width ,initial-scale=1'). PHP_EOL?>
<?= $this->headLink( )->appendStylesheet('/assets/bootstrap/dist/css/bootstrap.min.css'). PHP_EOL?>
<?= $this->headScript( ). PHP_EOL?>
<?= $this->headStyle(). PHP_EOL?>

</head>
<body>

	<div class="row affix-row">
		<div class="col-sm-3 col-md-2 affix-sidebar">
			<div class="sidebar-nav">
				<div class="navbar navbar-default" role="navigation">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse"
							data-target=".sidebar-navbar-collapse">
							<span class="sr-only">Toggle navigation</span> <span
								class="icon-bar"></span> <span class="icon-bar"></span> <span
								class="icon-bar"></span>
						</button>
						<span class="visible-xs navbar-brand">Sidebar menu</span>
					</div>
					<div class="navbar-collapse collapse sidebar-navbar-collapse">
						<ul class="nav navbar-nav" id="sidenav01">
							<li class="active"><a
								href="<?= $this->url(array(),'indexIndex')?>">
									<h4>My MVC</h4>
							</a></li>
							<li><a href="<?= $this->url(array(),'indexIndex')?>"><span
									class="glyphicon glyphicon-cloud"></span> Accueil </a></li>
							<li><a href="<?= $this->url(array(),'userListe')?>"><span class ="glyphicon glyphicon-list"></span> Liste</a></li>
			
							<li><a href=<?= $this->url(array(),'indexTest')?>><span
									class="glyphicon glyphicon-lock"></span> Test</a></li>
						</ul>
					</div>
					<!--/.nav-collapse -->
				</div>
			</div>
		</div>


		<div class="col-sm-9 col-md-10 affix-content">
			<div class="container">
				<div class="page-header">
                  <?= $this->layout()->content?>                 
            </div>
			</div>
		</div>
	</div>
    <? $this->inlineScript()->prependFile('/assets/bootstrap/dist/js/bootstrap.min.js'). PHP_EOL?>
    <?= $this->inlineScript()->prependFile('/assets/jquery/dist/jquery.min.js'). PHP_EOL?>
	
</body>
</html>